FROM node:8.2.1-slim
ENV PORT 80
# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json package-lock.json ./
RUN npm install
ENV NODE_ENV production

# Bundle app source
COPY . .

EXPOSE 80
CMD [ "npm", "start" ]