FROM acklenavenue/backend-sonarqube:8.8.1

# Create app directory
WORKDIR /usr/src/app

COPY package.json package-lock.json ./
COPY src/config/loggly.js.sample src/config/loggly.js
COPY src/config/sequelize.js.sample src/config/sequelize.js
RUN npm install

# Bundle app source
COPY . .

EXPOSE 3000
CMD [ "echo", "backend" ]