FROM node:8.2.1-slim

# Create app directory
WORKDIR /usr/code

# Install app dependencies
RUN apt-get update
RUN apt-get install unzip -y
RUN npm install gulp -g
RUN wget https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.0.3.778-linux.zip
RUN unzip sonar-scanner-cli-3.0.3.778-linux.zip
ENV PATH="/usr/code/sonar-scanner-3.0.3.778-linux/bin:${PATH}"
RUN sonar-scanner -h

COPY package.json .
RUN npm install

COPY src/config/loggly.js.sample /usr/code/src/config/loggly.js
COPY src/config/sequelize.js.sample /usr/code/src/config/sequelize.js

RUN ls -a src/config

# Bundle app source
COPY . .
EXPOSE 3000
CMD [ "echo", "backend" ]